create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  priority integer not null default 3 check (priority between 1 and 5),
  weight integer not null default 3 check (weight between 1 and 5),
  status text not null default 'pending',
  accuracy numeric not null default 0,
  questions_done integer not null default 0,
  errors integer not null default 0,
  last_studied_at date,
  next_review_at date,
  created_at timestamptz not null default now()
);

alter table public.topics add column if not exists module text not null default 'tj';

create table if not exists public.flashcards (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  difficulty integer not null default 3 check (difficulty between 1 and 5),
  topic_id bigint references public.topics(id) on delete cascade,
  next_review_at date not null default current_date,
  review_stage integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.flashcards add column if not exists module text not null default 'tj';

create table if not exists public.question_logs (
  id bigint generated by default as identity primary key,
  bank text not null default 'FCC',
  topic_id bigint references public.topics(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  correct integer not null default 0 check (correct >= 0),
  wrong integer not null default 0 check (wrong >= 0),
  logged_at date not null default current_date
);

alter table public.question_logs add column if not exists module text not null default 'tj';

create table if not exists public.simulations (
  id bigint generated by default as identity primary key,
  simulation_date date not null default current_date,
  total_questions integer not null default 70 check (total_questions > 0),
  correct integer not null default 0 check (correct >= 0),
  score numeric not null default 0,
  notes text not null default ''
);

alter table public.simulations add column if not exists module text not null default 'tj';

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.weak_points (
  id bigint generated by default as identity primary key,
  topic_id bigint references public.topics(id) on delete cascade,
  reason text not null,
  severity integer not null default 3 check (severity between 1 and 5),
  created_at timestamptz not null default now()
);

alter table public.topics enable row level security;
alter table public.flashcards enable row level security;
alter table public.question_logs enable row level security;
alter table public.simulations enable row level security;
alter table public.reports enable row level security;
alter table public.weak_points enable row level security;

drop policy if exists "public read topics" on public.topics;
drop policy if exists "public write topics" on public.topics;
drop policy if exists "public read flashcards" on public.flashcards;
drop policy if exists "public write flashcards" on public.flashcards;
drop policy if exists "public read question logs" on public.question_logs;
drop policy if exists "public write question logs" on public.question_logs;
drop policy if exists "public read simulations" on public.simulations;
drop policy if exists "public write simulations" on public.simulations;
drop policy if exists "public read reports" on public.reports;
drop policy if exists "public write reports" on public.reports;
drop policy if exists "public read weak points" on public.weak_points;
drop policy if exists "public write weak points" on public.weak_points;

create policy "public read topics" on public.topics for select using (true);
create policy "public write topics" on public.topics for all using (true) with check (true);
create policy "public read flashcards" on public.flashcards for select using (true);
create policy "public write flashcards" on public.flashcards for all using (true) with check (true);
create policy "public read question logs" on public.question_logs for select using (true);
create policy "public write question logs" on public.question_logs for all using (true) with check (true);
create policy "public read simulations" on public.simulations for select using (true);
create policy "public write simulations" on public.simulations for all using (true) with check (true);
create policy "public read reports" on public.reports for select using (true);
create policy "public write reports" on public.reports for all using (true) with check (true);
create policy "public read weak points" on public.weak_points for select using (true);
create policy "public write weak points" on public.weak_points for all using (true) with check (true);

create index if not exists topics_category_idx on public.topics(category);
create index if not exists topics_module_idx on public.topics(module);
create index if not exists topics_priority_idx on public.topics(priority desc);
create index if not exists flashcards_module_idx on public.flashcards(module);
create index if not exists flashcards_next_review_idx on public.flashcards(next_review_at);
create index if not exists question_logs_module_idx on public.question_logs(module);
create index if not exists question_logs_logged_at_idx on public.question_logs(logged_at desc);
create index if not exists simulations_module_idx on public.simulations(module);
